Resources/config/binlog.yml
Resources/doc/sync_storage.rst

Refactor service class and fix documentation issues.

---

Resources/doc/sync_storage.rst

Fix documentation issues.

---

EventListener/SyncExecuteConsumeEventListener.php
Sync/ActionTypes.php
Sync/Extractor/DoctrineExtractor.php
Sync/Extractor/PassthroughExtractor.php
Sync/Extractor/Relation/SimpleSqlRelation.php
Sync/SyncStorage/SyncStorage.php
Sync/SyncStorage/SyncStorageInterface.php
Sync/SyncStorageImportIterator.php
Tests/Functional/Command/SyncProvideCommandTest.php
Tests/Functional/Fixtures/SyncCommandsTest/SyncStorageWithDummyData.sql
Tests/Functional/Sync/Extractor/DoctrineExtractorTest.php
Tests/Functional/Sync/Extractor/PassthroughExtractorTest.php
Tests/Functional/Sync/SyncStorage/StorageManager/MysqlStorageManagerTest.php
Tests/Functional/Sync/SyncStorage/SyncStorageTest.php
Tests/Unit/Command/SyncProvideCommandTest.php
Tests/Unit/EventListener/SyncExecuteConsumeEventListenerTest.php
Tests/Unit/Import/SyncExecuteItemTest.php
Tests/Unit/Sync/Extractor/PassthroughExtractorTest.php
Tests/Unit/Sync/JobManagerTest.php
Tests/Unit/Sync/SyncStorage/SyncStorageImportIteratorTest.php

Changed SyncStorageInterface constant values to uppercase.

---

Tests/Functional/ESDoctrineTestCase.php

Test case now correctly locates DoctrineAnnotations when bundle is in vendor directory

---

EventListener/AbstractConsumeEventListener.php
EventListener/AbstractImportConsumeEventListener.php
EventListener/DataSyncConsumeEventListener.php
LICENSE
Pipeline/Event/ItemPipelineEvent.php
Pipeline/ItemSkipException.php
Pipeline/Pipeline.php
Tests/Functional/Fixtures/ItemUrlInvalidator/DummyItemInvalidator.php
Tests/Unit/Pipeline/PipelineTest.php
Tests/Unit/Pipeline/PipelineTestConsumer.php
UrlInvalidator/AbstractItemUrlInvalidator.php

Pipeline item skip mechanism.

---

Resources/config/extractor.yml
Sync/Extractor/AbstractExtractor.php
Sync/Extractor/DoctrineExtractor.php
Sync/Extractor/PassthroughExtractor.php
Sync/StorageManager/MysqlStorageManager.php
Tests/Functional/Command/SyncProvideCommandTest.php
Tests/Functional/Sync/Extractor/PassthroughExtractorTest.php
Tests/Unit/Sync/Extractor/PassthroughExtractorTest.php
Tests/app/config/parameters_test.yml

Fix multiple shop id functionality.

---

EventListener/AbstractConsumeEventListener.php
Pipeline/Event/ItemPipelineEvent.php
Pipeline/ItemSkipException.php
Pipeline/Pipeline.php
Resources/doc/pipeline.rst
Tests/Unit/Pipeline/PipelineTest.php
Tests/Unit/Pipeline/PipelineTestConsumer.php

Comments from https://github.com/ongr-io/ConnectionsBundle/pull/99

Fixed Tautrimas comments and added basic pipeline documentation.

---

Command/SyncParametersCommand.php
Sync/DiffProvider/Binlog/BinlogDiffProvider.php
Tests/Functional/Command/SyncParametersCommandTest.php
Tests/Functional/Command/SyncProvideCommandTest.php
Tests/Unit/Command/SyncParametersCommandTest.php

Fix parameter command

---

README.rst

Fix bad link in readme.rst

---

Tests/Functional/Command/ImportFullCommandTest.php
Tests/Functional/Command/SyncExecuteCommandTest.php
Tests/Functional/Service/PairStorageTest.php
Tests/Unit/Service/PairStorageTest.php

Fix compatability errors with v0.5.0 ESB update

---

Pipeline/Pipeline.php
Tests/Unit/Pipeline/PipelineTest.php

Pipeline should now allow context modification at any point

---

EventListener/AbstractImportModifyEventListener.php
Sync/Extractor/DoctrineExtractor.php
Sync/StorageManager/MysqlStorageManager.php
Tests/Functional/Command/SyncProvideCommandTest.php
Tests/Functional/Sync/SyncStorage/StorageManager/MysqlStorageManagerTest.php
Tests/Unit/EventListener/AbstractImportModifyEventListenerTest.php

Storage deduction for DELETE action.

---

Tests/Unit/Command/AbstractStartServiceCommandTest.php
Tests/Unit/Pipeline/PipelineStarterTest.php

Added missing tests.

---

EventListener/AbstractImportConsumeEventListener.php
EventListener/AbstractImportModifyEventListener.php
EventListener/SyncExecuteConsumeEventListener.php
Tests/Unit/EventListener/AbstractImportModifyEventListenerTest.php
Tests/Unit/EventListener/ImportConsumeEventListenerTest.php
Tests/Unit/EventListener/SyncExecuteConsumeEventListenerTest.php

Change log level for inconsistencies.

---

Resources/config/import.yml

Changed import pipeline services to abstract.

---

EventListener/AbstractImportConsumeEventListener.php
EventListener/AbstractImportModifyEventListener.php
Tests/Unit/EventListener/ImportConsumeEventListenerTest.php
Tests/Unit/EventListener/SyncExecuteConsumeEventListenerTest.php

remove old logic

---

DependencyInjection/Compiler/ModifierClassPass.php
ONGRConnectionsBundle.php
Tests/app/config/services.yml

Now abstract sevice is more useful.

Added modifier class pass

---

Resources/config/binlog.yml
Resources/config/extractor.yml
Sync/Extractor/DoctrineExtractor.php
Tests/Unit/Sync/Extractor/DoctrineExtractorTest.php
composer.json

Doctrine dependency is now optional.

---

Document/Pair.php
Service/PairStorage.php
Tests/Unit/Service/PairStorageTest.php
composer.json

Closes #176 
**MERGE AFTER `ongr/elasticsearch-bundle 0.9` RELEASE!**

Incompabilities with new ESB release

---

Tests/Functional/AbstractTestCase.php

- Added removed by merge/commit changes.

Fixed functional AbstractTestCase.

---

.travis.yml
Tests/Functional/Command/SyncProvideCommandTest.php
Tests/Functional/Fixtures/Bundles/Acme/TestBundle/Document/Item.php
Tests/Functional/Sync/Extractor/DoctrineExtractorTest.php
Tests/Unit/EventListener/LoadClassMetadataListenerTest.php
UrlInvalidator/UrlInvalidatorService.php
composer.json

Updated bundle to use strict standard 2.0.

---

DependencyInjection/Configuration.php
DependencyInjection/ONGRConnectionsExtension.php
EventListener/AbstractImportConsumeEventListener.php
EventListener/AbstractImportSourceEventListener.php
EventListener/DataSyncConsumeEventListener.php
EventListener/DataSyncSourceEventListener.php
EventListener/ImportConsumeEventListener.php
EventListener/ImportFinishEventListener.php
EventListener/ImportSourceEventListener.php
EventListener/ModifyEventListener.php
EventListener/SyncExecuteConsumeEventListener.php
EventListener/SyncExecuteSourceEventListener.php
Service/ShopService.php
Tests/Functional/Command/SyncProvideCommandTest.php
Tests/Functional/Service/ShopServiceTest.php
Tests/Unit/DependencyInjection/ONGRConnectionsExtensionTest.php
Tests/app/config/config_test.yml

Made DI possible through setters for event listeners.
Added setters and getters for properties.
Using getters instead of directly accessing properties.
Made properties private.
Made naming consistent between managers, documents and entities.
Added shop service for simple shop information retrieval.

Service generator
